#builder
FROM golang:1.23.3-alpine AS builder

RUN apk add --no-cache make gcc musl-dev

WORKDIR /home

COPY .. /home
COPY events/Makefile /home/Makefile

# собираем
RUN make build-events


# events
FROM alpine:latest AS server

ARG GITHUB_PATH=github.com/arslanovdi/logistic-package

LABEL org.opencontainers.image.source=https://${GITHUB_PATH}

RUN apk --no-cache add ca-certificates curl

WORKDIR /root/
RUN mkdir config  # папка для монтирования конфигурации из k8s ConfigMap
# копируем все что нужно для работы приложения
COPY --from=builder /home/bin/events .
COPY --from=builder /home/events/config.yml /root/config/config.yml

RUN chown root:root events

EXPOSE 8000
EXPOSE 9100

CMD ["./events", "-config=config/config.yml"]
