#builder
FROM golang:1.23.3-bullseye AS builder

COPY events/Makefile /home/Makefile
COPY go.mod /home
COPY go.sum /home

WORKDIR /home

COPY .. /home

# собираем
RUN make build-events


# events
FROM golang:1.23.3-bullseye AS server

ARG GITHUB_PATH=github.com/arslanovdi/logistic-package/events

LABEL org.opencontainers.image.source=https://${GITHUB_PATH}

WORKDIR /root/
# копируем все что нужно для работы приложения
COPY --from=builder /home/bin/events .
COPY --from=builder /home/events/config.yml .

RUN chown root:root events

CMD ["./events", "-config=config.yml"]
