#builder
FROM golang:1.23.3-bullseye AS builder

COPY logistic-package-api/Makefile /home/Makefile
COPY go.mod /home
COPY go.sum /home

WORKDIR /home

COPY .. /home

# собираем
RUN make build-outbox


# retranslator
FROM golang:1.23.3-bullseye AS server

ARG GITHUB_PATH=github.com/arslanovdi/logistic-package/logistic-package-api

LABEL org.opencontainers.image.source=https://${GITHUB_PATH}

WORKDIR /root/
# копируем все что нужно для работы приложения
COPY --from=builder /home/bin/retranslator .
COPY --from=builder /home/logistic-package-api/config.yml .

RUN chown root:root retranslator

EXPOSE 8000

CMD ["./retranslator", "-config=config.yml"]
