#builder
FROM golang:1.24.2-alpine AS builder

RUN apk add --no-cache make gcc musl-dev

COPY logistic-package-api/Makefile /home/Makefile
COPY go.mod /home
COPY go.sum /home

WORKDIR /home

COPY .. /home
COPY logistic-package-api/Makefile /home/Makefile

# собираем
RUN make build-outbox


# retranslator
FROM alpine:latest AS server

ARG GITHUB_PATH=github.com/arslanovdi/logistic-package

LABEL org.opencontainers.image.source=https://${GITHUB_PATH}

RUN apk --no-cache add ca-certificates curl

WORKDIR /root/
RUN mkdir config  # папка для монтирования конфигурации из k8s ConfigMap
# копируем все что нужно для работы приложения
COPY --from=builder /home/bin/retranslator .
COPY --from=builder /home/logistic-package-api/config.yml /root/config/config.yml

RUN chown root:root retranslator

EXPOSE 8000
EXPOSE 9100

CMD ["./retranslator", "-config=config/config.yml"]
