#builder
FROM golang:1.23.3-alpine AS builder

RUN apk add --no-cache make

COPY telegram_bot/Makefile /home/Makefile
COPY go.mod /home
COPY go.sum /home

WORKDIR /home

COPY .. /home
COPY telegram_bot/Makefile /home/Makefile

# собираем
RUN make build-tgbot


# tgbot
FROM alpine:latest AS server

ARG GITHUB_PATH=github.com/arslanovdi/logistic-package

LABEL org.opencontainers.image.source=https://${GITHUB_PATH}

RUN apk --no-cache add ca-certificates curl

WORKDIR /root/
RUN mkdir config  # папка для монтирования конфигурации из k8s ConfigMap
# копируем все что нужно для работы приложения
COPY --from=builder /home/bin/tg_bot .
COPY --from=builder /home/telegram_bot/config.yml /root/config/config.yml


RUN chown root:root tg_bot

EXPOSE 8000
EXPOSE 9100

CMD ["./tg_bot", "-config=config/config.yml"]
