# syntax=docker/dockerfile:1-labs
#builder
FROM golang:1.23.3-bullseye AS builder

COPY Makefile /home/Makefile

COPY go.mod /home
COPY go.sum /home

WORKDIR /home


COPY logistic-package-api/. /home
COPY pkg/. /home/pkg

# собираем
RUN make build-outbox

# outbox

FROM golang:1.23.3-bullseye AS server

ARG GITHUB_PATH=github.com/arslanovdi/logistic-package/logistic-package-api

LABEL org.opencontainers.image.source=https://${GITHUB_PATH}

WORKDIR /root/
# копируем все что нужно для работы приложения
COPY --from=builder /home/bin/retranslator .
COPY --from=builder /home/config.yml .
COPY --from=builder /home/migrations/ ./migrations

RUN chown root:root retranslator

EXPOSE 8000

CMD ["./retranslator"]
