# syntax=docker/dockerfile:1.7-labs
#builder
FROM golang:1.23.3-bullseye AS builder

COPY telegram_bot/Makefile /home/Makefile
COPY go.mod /home
COPY go.sum /home

WORKDIR /home

COPY .. /home

# собираем
RUN make build-tgbot

# outbox

FROM golang:1.23.3-bullseye AS server

ARG GITHUB_PATH=github.com/arslanovdi/logistic-package/telegram_bot

LABEL org.opencontainers.image.source=https://${GITHUB_PATH}

WORKDIR /root/
# копируем все что нужно для работы приложения
COPY --from=builder /home/bin/tg_bot .
COPY --from=builder /home/telegram_bot/config.yml telegram_bot/config.yml

RUN chown root:root tg_bot

CMD ["./tg_bot"]
