#builder
FROM golang:1.23.3-alpine AS builder

RUN apk add --no-cache make curl

COPY logistic-package-api/Makefile /home/Makefile
COPY go.mod /home
COPY go.sum /home

WORKDIR /home

RUN make deps-go

COPY .. /home
COPY logistic-package-api/Makefile /home/Makefile

# собираем
RUN make build-go


# gRPC Server
FROM alpine:latest AS server

ARG GITHUB_PATH=github.com/arslanovdi/logistic-package

LABEL org.opencontainers.image.source=https://${GITHUB_PATH}

RUN apk --no-cache add ca-certificates curl

WORKDIR /root/
RUN mkdir config  # папка для монтирования конфигурации из k8s ConfigMap
# копируем все что нужно для работы приложения
COPY --from=builder /home/bin/grpc-server .
COPY --from=builder /home/logistic-package-api/config.yml /root/config/config.yml
COPY --from=builder /home/logistic-package-api/migrations/ ./migrations
COPY --from=builder /home/logistic-package-api/swagger ./swagger
COPY --from=builder /home/logistic-package-api/swagger-ui ./swagger-ui

RUN chown root:root grpc-server

EXPOSE 8080
EXPOSE 8082
EXPOSE 9100
EXPOSE 8000


CMD ["./grpc-server", "-config=config/config.yml"]