apiVersion: v1
kind: Service
metadata:
  labels:
    app: schemaregistry
  name: schemaregistry
  namespace: kafka
spec:
  clusterIP: None
  ports:
    - name: "listener"
      port: 8081
      targetPort: 8081
  selector:
    app: schemaregistry