apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: logistic-package-events
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 20
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824