apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: observability
spec:
  type: ClusterIP
  ports:
    - name: "http-web-graylog"
      port: 9000
      targetPort: 9000
    - name: "tcp-gelf"
      port: 12201
      targetPort: 12201
      protocol: TCP
    - name: "udp-gelf"
      port: 12201
      protocol: UDP
      targetPort: 12201
  selector:
    app: graylog

