apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-ui
  name: kafka-ui
  namespace: kafka
spec:
  type: ClusterIP
  ports:
    - name: "kafka-ui"
      port: 8080
      targetPort: 8080
  selector:
    app: kafka-ui
