apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: logistic-package
spec:
  selector:
    istio: ingressgateway   # use istio default ingress gateway
  servers:
    - port:
        number: 80
        name: swagger
        protocol: HTTP
      hosts:
        - "swagger.k3s.dev.com"

