apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: observability
spec:
  clusterIP: None
  ports:
    - name: "tcp-mongodb"
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb
