apiVersion: apps/v1
kind: Deployment
metadata:
  name: schemaregistry
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schemaregistry
  template:
    metadata:
      labels:
        app: schemaregistry
    spec:
      containers:
        - name: schemaregistry
          image: confluentinc/cp-schema-registry:7.7.1
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
          ports:
            - containerPort: 8081
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 90
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: schemaregistry
            - name: SCHEMA_REGISTRY_INTER_INSTANCE_LISTENER_NAME
              value: schemaregistry
            - name: SCHEMA_REGISTRY_INTER_INSTANCE_PROTOCOL
              value: http
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: kafka-cluster-kafka-bootstrap.kafka:9092
            - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: SCHEMA_REGISTRY_KAFKASTORE_TOPIC
              value: _schemas
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://schemaregistry:8081
            - name: SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL
              value: INFO