apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - name: graylog
          image: graylog/graylog:6.1.4-1
          command:
            - /usr/bin/tini
            - --
            - wait-for-it
            - opensearch-node:9200
            - --
            - /docker-entrypoint.sh
          resources:
            requests:
              memory: "128Mi"
              cpu: "25m"
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 12201
              protocol: TCP
            - containerPort: 12201
              protocol: UDP
          env:
            - name: GRAYLOG_PASSWORD_SECRET
              value: somepasswordpepper
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918   # admin
            - name: GRAYLOG_BIND_ADDRESS
              value: 0.0.0.0:9000
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: http://graylog.k3s.dev.com/
            - name: GRAYLOG_HTTP_PUBLISH_URI
              value: http://graylog.k3s.dev.com/
            - name: GRAYLOG_MONGODB_URI
              value: mongodb://mongodb:27017/graylog
            - name: GRAYLOG_ELASTICSEARCH_HOSTS
              value: http://opensearch-node:9200
          volumeMounts:
            - mountPath: /usr/share/graylog/data/data
              name: graylog-data
      volumes:
        - name: graylog-data
          persistentVolumeClaim:
            claimName: graylog-data-pvc

