apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one
          resources:
            requests:
              memory: "1Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4317
              protocol: TCP
              name: "grpc"
            - containerPort: 16686
              protocol: TCP
              name: "web-ui"
          livenessProbe:
            httpGet:
              path: "/"
              port: 14269
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: "/"
              port: 14269
            initialDelaySeconds: 5
