apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-ui
  name: kafka-ui
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "350Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
              name: "kafka-ui"
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
          env:
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS
              value: kafka-cluster-kafka-brokers:9092
            - name: KAFKA_CLUSTERS_0_METRICS_PORT
              value: "9999"
            - name: KAFKA_CLUSTERS_0_METRICS_TYPE
              value: JMX
            - name: KAFKA_CLUSTERS_0_NAME
              value: "kafka-cluster"
            - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
              value: http://schemaregistry:8081

