apiVersion: v1
kind: Service
metadata:
  labels:
    app: logistic-package-api
  name: logistic-package-api
  namespace: logistic-package
spec:
  type: ClusterIP
  ports:
    - name: "tcp-grpc"
      port: 8082
      targetPort: 8082
      protocol: TCP
    - name: "tcp-grpc-gateway"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: logistic-package-api

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: logistic-package-api
  name: logistic-package-api-headless
  namespace: logistic-package
spec:
  clusterIP: None
  ports:
    - name: "tcp-metrics"
      port: 9100
      targetPort: 9100
      protocol: TCP
    - name: "tcp-status"
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: logistic-package-api
