apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: observability
spec:
  type: ClusterIP
  ports:
    - name: "tcp-prometheus-ui"
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus

