apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: telegram
  namespace: logistic-package
spec:
  hosts:
    - api.telegram.org
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
