apiVersion: v1
kind: Service
metadata:
  labels:
    app: tgbot
  name: tgbot-headless
  namespace: logistic-package
spec:
  clusterIP: None
  #type: ClusterIP
  ports:
    - name: "tcp-metrics"
      port: 9100
      targetPort: 9100
      protocol: TCP
    - name: "tcp-status"
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: tgbot
