// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/arslanovdi/logistic-package/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// Repo is an autogenerated mock type for the Repo type
type Repo struct {
	mock.Mock
}

type Repo_Expecter struct {
	mock *mock.Mock
}

func (_m *Repo) EXPECT() *Repo_Expecter {
	return &Repo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, pkg
func (_m *Repo) Create(ctx context.Context, pkg *model.Package) (*uint64, error) {
	ret := _m.Called(ctx, pkg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Package) (*uint64, error)); ok {
		return rf(ctx, pkg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Package) *uint64); ok {
		r0 = rf(ctx, pkg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Package) error); ok {
		r1 = rf(ctx, pkg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - pkg *model.Package
func (_e *Repo_Expecter) Create(ctx interface{}, pkg interface{}) *Repo_Create_Call {
	return &Repo_Create_Call{Call: _e.mock.On("Create", ctx, pkg)}
}

func (_c *Repo_Create_Call) Run(run func(ctx context.Context, pkg *model.Package)) *Repo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Package))
	})
	return _c
}

func (_c *Repo_Create_Call) Return(_a0 *uint64, _a1 error) *Repo_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_Create_Call) RunAndReturn(run func(context.Context, *model.Package) (*uint64, error)) *Repo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repo) Delete(ctx context.Context, id uint64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *Repo_Expecter) Delete(ctx interface{}, id interface{}) *Repo_Delete_Call {
	return &Repo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *Repo_Delete_Call) Run(run func(ctx context.Context, id uint64)) *Repo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *Repo_Delete_Call) Return(_a0 error) *Repo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_Delete_Call) RunAndReturn(run func(context.Context, uint64) error) *Repo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *Repo) Get(ctx context.Context, id uint64) (*model.Package, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*model.Package, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *model.Package); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint64
func (_e *Repo_Expecter) Get(ctx interface{}, id interface{}) *Repo_Get_Call {
	return &Repo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *Repo_Get_Call) Run(run func(ctx context.Context, id uint64)) *Repo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *Repo_Get_Call) Return(_a0 *model.Package, _a1 error) *Repo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_Get_Call) RunAndReturn(run func(context.Context, uint64) (*model.Package, error)) *Repo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, offset, limit
func (_m *Repo) List(ctx context.Context, offset uint64, limit uint64) ([]model.Package, error) {
	ret := _m.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Package
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]model.Package, error)); ok {
		return rf(ctx, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []model.Package); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Package)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - offset uint64
//   - limit uint64
func (_e *Repo_Expecter) List(ctx interface{}, offset interface{}, limit interface{}) *Repo_List_Call {
	return &Repo_List_Call{Call: _e.mock.On("List", ctx, offset, limit)}
}

func (_c *Repo_List_Call) Run(run func(ctx context.Context, offset uint64, limit uint64)) *Repo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(uint64))
	})
	return _c
}

func (_c *Repo_List_Call) Return(_a0 []model.Package, _a1 error) *Repo_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repo_List_Call) RunAndReturn(run func(context.Context, uint64, uint64) ([]model.Package, error)) *Repo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, pkg
func (_m *Repo) Update(ctx context.Context, pkg *model.Package) error {
	ret := _m.Called(ctx, pkg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Package) error); ok {
		r0 = rf(ctx, pkg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - pkg *model.Package
func (_e *Repo_Expecter) Update(ctx interface{}, pkg interface{}) *Repo_Update_Call {
	return &Repo_Update_Call{Call: _e.mock.On("Update", ctx, pkg)}
}

func (_c *Repo_Update_Call) Run(run func(ctx context.Context, pkg *model.Package)) *Repo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Package))
	})
	return _c
}

func (_c *Repo_Update_Call) Return(_a0 error) *Repo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repo_Update_Call) RunAndReturn(run func(context.Context, *model.Package) error) *Repo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepo creates a new instance of Repo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repo {
	mock := &Repo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
