apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: logistic-package
spec:
  type: ClusterIP
  ports:
    - name: "http-grafana"
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
  sessionAffinity: None
