project:
    name: Logistic Package Telegram Bot
    debug: false
    environment: development
    instance: "logistic-package-telegram_bot"
    startupTimeout: 60  # seconds
    shutdownTimeout: 30  # seconds

grpc:
  host: logistic-package-api
  port: 8082
  ctxTimeout: 10s

jaeger:
  host: "jaeger"
  port: ":4317" # grpc 4317; http 6831

telegram:
  faker: false
  timeout: 60 # seconds
  token: 7012140868:AAHAkiK606qFalhnX7Cm3d8aDRTIw5m3NWw

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version