project:
    name: Logistic Package Telegram Bot
    debug: true
    environment: development
    instance: "logistic-package-telegram_bot-1"
    startupTimeout: 60  # seconds
    shutdownTimeout: 30  # seconds

grpc:
  host: localhost
  port: 8082
  ctxTimeout: 5s

jaeger:
  host: localhost
  port: ":4317" # grpc 4317; http 6831

telegram:
  faker: true
  timeout: 60 # seconds
  token: 7012140868:AAHAkiK606qFalhnX7Cm3d8aDRTIw5m3NWw

metrics:
  host: 0.0.0.0
  port: 9101
  path: /metrics

status:
  host: 0.0.0.0
  port: 8001
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version