events:
  image:
    repository: arslanovdi/logistic-package
    tag: v0.1.3
  replicas: 3

tgbot:
  image:
    repository: arslanovdi/logistic-package
    tag: v0.1.2

logistic_package_api:
  image:
    repository: arslanovdi/logistic-package
    tag: v0.1.8

retranslator:
  image:
    repository: arslanovdi/logistic-package
    tag: v0.1.3

