quiet: False  # не выводить предупреждения

disable-version-string: True

issue-845-fix: True

with-expecter: True # генерировать expecter, рекомендовано включить

dir: "mocks/"
mockname: "{{.InterfaceName}}"  # имя сгенерированного интерфейса
filename: "{{.MockName}}.go"  # имя файла

outpkg: mocks # пакет со сгенерированными интерфейсами

packages:
  github.com/arslanovdi/logistic-package/logistic-package-api/internal/service:
    interfaces:
      Repo:
  github.com/arslanovdi/logistic-package/logistic-package-api/internal/outbox/repo:
    interfaces:
      EventRepo:
  github.com/arslanovdi/logistic-package/logistic-package-api/internal/outbox/sender:
    interfaces:
      EventSender:
