project:
  name: Ozon Marketplace Logistic Package API
  debug: true
  environment: development
  instance: "logistic-package-api-1"
  startupTimeout: 60  # seconds
  shutdownTimeout: 5  # seconds

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 5 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8080

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

jaeger:
  service: "logistic-package-api"
  host: "127.0.0.1" #"jaeger" #
  port: ":4317"   # grpc 4317; http 6831

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

database:
  host: localhost #postgres #
  port: 5432
  user: logistic
  password: P@$$w0rd
  name: logistic_package_api
  sslmode: disable
  migrations: migrations
  driver: pgx
  queryTimeout: 5 # seconds query timeout

kafka:
  capacity: 512
  topic: "logistic-package-events"
  groupId: "logistic-package-api"
  flushTimeout: 5000 # milliseconds
  brokers:
    - "localhost:29092" #- "kafka1:9092" #
    - "localhost:29093" #- "kafka2:9092" #
    - "localhost:29094" #- "kafka3:9092" #
  schemaregistry:  "http://localhost:8081" #"http://schemaregistry1:8081"

outbox:
  batchSize: 100    # кол-во событий получаемых за один запрос из БД
  ticker: 10        # load events every ticker seconds
  producerCount: 20 # кол-во горутин продюсеров, отправляющих в кафку