project:
  name: Logistic Package API
  debug: true
  environment: development
  instance: "logistic-package-api"
  startupTimeout: 60  # seconds
  shutdownTimeout: 30  # seconds

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 5 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8080

metrics:
  host: 0.0.0.0
  port: 9102
  path: /metrics

jaeger:
  host: "127.0.0.1"
  port: ":4317"   # grpc 4317; http 6831

status:
  host: 0.0.0.0
  port: 8002
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

database:
  host: localhost #postgres #
  port: 5432
  user: logistic
  password: P@$$w0rd
  name: logistic_package_api
  ssl: disable
  migrations: logistic-package-api/migrations
  driver: pgx
  queryTimeout: 5 # seconds query timeout

kafka:
  topic: "logistic-package-events"
  groupId: "logistic-package-api"
  flushTimeout: 5000 # milliseconds
  brokers:
    - "localhost:29092"
    - "localhost:29093"
    - "localhost:29094"
  schemaRegistry:  "http://localhost:8081"

outbox:
  batchSize: 100    # кол-во событий получаемых за один запрос из БД
  ticker: 10        # load events every ticker seconds
  producerCount: 20 # кол-во потоков, отправляющих в кафку

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  ttl: 600 # seconds
  retryDuration: 10 # seconds