project:
  name: Logistic Package API
  debug: true
  environment: development
  instance: "logistic-package-events-1"
  startupTimeout: 60  # seconds
  shutdownTimeout: 30  # seconds

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

jaeger:
  host: "jaeger"
  port: ":4317"   # grpc 4317; http 6831

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

kafka:
  topic: "logistic-package-events"
  groupId: "logistic-package-events"
  brokers:
    - "kafka1:9091"
    - "kafka2:9091"
    - "kafka3:9091"
  schemaregistry:  "http://schemaregistry1:8081"
