project:
  name: Logistic Package API
  debug: true
  environment: development
  instance: "logistic-package-events-1"
  startupTimeout: 60  # seconds
  shutdownTimeout: 30  # seconds

metrics:
  host: 0.0.0.0
  port: 9101
  path: /metrics

jaeger:
  host: "127.0.0.1" #"jaeger" #
  port: ":4317"   # grpc 4317; http 6831

status:
  host: 0.0.0.0
  port: 8002
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

kafka:
  topic: "logistic-package-events"
  groupId: "logistic-package-events"
  consumerCount: 1
  brokers:
    - "localhost:29092" #"kafka1:9091"
    - "localhost:29093" #"kafka2:9091"
    - "localhost:29094" #"kafka3:9091"
  schemaregistry:  "http://localhost:8081" #"http://schemaregistry1:8081"
