# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

env:
  GO_VERSION: 1.23.3
  GOLANGCI_LINT_VERSION: v1.63.4

jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build events
      run: go build -o bin -v ./events/cmd/events/...

    - name: Build logistic-package-api
      run: go build -v ./logistic-package-api/cmd/grpc-server/...

    - name: Build retranslator
      run: go build -v ./logistic-package-api/cmd/retranslator/...

    - name: Build tgbot
      run: go build -v ./telegram_bot/cmd/bot/...

    - name: Test
      run: go test -v ./...

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: ${{ env.GOLANGCI_LINT_VERSION }}
        args: --timeout=30m --config=golangci.yml --issues-exit-code=0
